# Generated by Django 4.1.5 on 2023-02-06 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=120)),
                ('project_type', models.IntegerField(choices=[(1, 'professional'), (0, 'handyman')])),
                ('description', models.TextField()),
                ('budget', models.PositiveIntegerField()),
                ('status', models.IntegerField(choices=[(0, 'available'), (1, 'ongoing'), (2, 'complete')])),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
