# Generated by Django 4.1.5 on 2023-02-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_project_user_project_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.IntegerField(choices=[('PROFESSIONAL', 'PROFESSIONAL'), ('HANDYMAN', 'HANDYMAN')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[('available', 'available'), ('ongoing', 'ongoing'), ('complete', 'complete')]),
        ),
    ]
