# Generated by Django 4.1.5 on 2023-02-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_project_city_alter_project_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('PROFESSIONAL', 'PROFESSIONAL'), ('HANDYMAN', 'HANDYMAN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('ongoing', 'ongoing'), ('complete', 'complete')], max_length=20),
        ),
    ]
