# Generated by Django 4.1.5 on 2023-02-12 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_project_project_type_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(default='', max_length=30, null=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='project_skill', to='jobs.project')),
            ],
        ),
    ]
