# Generated by Django 4.1.5 on 2023-02-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_project_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_skill',
            old_name='user',
            new_name='project',
        ),
    ]
