# Generated by Django 4.1.5 on 2023-02-12 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_rename_user_project_skill_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('ongoing', 'ongoing'), ('complete', 'complete')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='project_skill',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='jobs.project'),
        ),
    ]
