# Generated by Django 4.1.5 on 2023-01-28 14:25

import accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(default='', max_length=100, unique=True)),
                ('institute', models.CharField(default='', max_length=100)),
                ('graduation_year', models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1900), accounts.models.max_value_current_year])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
