# Generated by Django 4.1.5 on 2023-01-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(default='', max_length=30, null=True, unique=True),
        ),
    ]
