# Generated by Django 4.1.5 on 2023-01-29 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_skill_user_skill_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ManyToManyField(default='', related_name='skill', to=settings.AUTH_USER_MODEL),
        ),
    ]
