# Generated by Django 4.1.5 on 2023-02-02 10:44

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_skill_user_skill_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_year',
            field=models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1960), accounts.models.max_value_current_year]),
        ),
    ]
