# Generated by Django 4.1.5 on 2023-02-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_education_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_description',
        ),
    ]
