# Generated by Django 4.1.5 on 2023-02-11 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_profile_age_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='graduation_year',
            field=models.CharField(max_length=4),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100, null=True)),
                ('start_year', models.CharField(max_length=4)),
                ('end_year', models.CharField(max_length=10)),
                ('description', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
